Repository CMPUT301F20T41/boromi, pull requests merged in 2020-11, with the labels that each got.

#53 Ming/book request for #27
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/team41/boromi/BookActivity.java
  app/src/main/java/com/team41/boromi/BoromiApp.java
  app/src/main/java/com/team41/boromi/FragmentFactory.java
  app/src/main/java/com/team41/boromi/MainActivity.java
  app/src/main/java/com/team41/boromi/TestActivity.java
  app/src/main/java/com/team41/boromi/TestRequestBookActivity.java
  app/src/main/java/com/team41/boromi/adapters/PagerAdapter.java
  app/src/main/java/com/team41/boromi/callbacks/BookRequestCallback.java
  app/src/main/java/com/team41/boromi/controllers/AuthenticationController.java
  app/src/main/java/com/team41/boromi/controllers/BookRequestController.java
  app/src/main/java/com/team41/boromi/dagger/ActivityScope.java
  app/src/main/java/com/team41/boromi/dagger/AppComponent.java
  app/src/main/java/com/team41/boromi/dagger/AuthenticationComponent.java
  app/src/main/java/com/team41/boromi/dagger/BoromiModule.java
  app/src/main/java/com/team41/boromi/dagger/FirestoreModule.java
  app/src/main/java/com/team41/boromi/dbs/BookDB.java
  app/src/main/java/com/team41/boromi/dbs/BookRequestDB.java
  app/src/main/java/com/team41/boromi/dbs/UserDB.java
  app/src/main/java/com/team41/boromi/models/Book.java
  app/src/main/java/com/team41/boromi/models/BookRequest.java
  app/src/main/java/com/team41/boromi/models/BookReturn.java
  app/src/main/java/com/team41/boromi/models/User.java
  app/src/main/res/layout/activity_test_request_book.xml
Labels: Priority: Critical, Type: Core

#55 simple logic for auth to reeset pass
  app/src/main/java/com/team41/boromi/TestActivity.java
  app/src/main/java/com/team41/boromi/controllers/AuthenticationController.java
Labels: Priority: High, Type: Enhancement

#51 UserDB & AuthenticationController: Fixes, Checks, Tests
  app/build.gradle
  app/src/androidTest/java/com/team41/boromi/AuthenticationControllerTest.java
  app/src/androidTest/java/com/team41/boromi/UserDBTest.java
  app/src/main/java/com/team41/boromi/controllers/AuthenticationController.java
  app/src/main/java/com/team41/boromi/dbs/UserDB.java
  app/src/main/java/com/team41/boromi/models/User.java
Labels: Length: Less than 5 Hours, Priority: Critical

#56 Backend logic for request returns - issue #52
  app/src/androidTest/java/com/team41/boromi/BookControllerTest.java
  app/src/androidTest/java/com/team41/boromi/BookReturnsDBTest.java
  app/src/main/java/com/team41/boromi/BookActivity.java
  app/src/main/java/com/team41/boromi/MainActivity.java
  app/src/main/java/com/team41/boromi/callbacks/ReturnCallback.java
  app/src/main/java/com/team41/boromi/controllers/BookReturnController.java
  app/src/main/java/com/team41/boromi/dagger/AppComponent.java
  app/src/main/java/com/team41/boromi/dbs/BookDB.java
  app/src/main/java/com/team41/boromi/dbs/BookReturnDB.java
  app/src/main/java/com/team41/boromi/models/Book.java
  app/src/main/java/com/team41/boromi/models/BookReturn.java
  app/src/main/res/layout/activity_book.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_borrowed.xml
  app/src/main/res/layout/fragment_generic_list.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_owned.xml
  app/src/main/res/layout/fragment_recover_password.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/layout/fragment_welcome.xml
Labels: Length: 5-10 Hours, Priority: Critical, Type: Core

#63 Brock/core #60
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/team41/boromi/BookActivity.java
  app/src/main/java/com/team41/boromi/book/EditUserFragment.java
  app/src/main/java/com/team41/boromi/book/SettingsFragment.java
  app/src/main/res/drawable/logout_icon.xml
  app/src/main/res/layout/fragment_edit_user.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Length: Less than 5 Hours

#66 Brock/core #64 - Add Change Auth Email Method
  app/src/androidTest/java/com/team41/boromi/AuthenticationControllerTest.java
  app/src/androidTest/java/com/team41/boromi/BookControllerTest.java
  app/src/main/java/com/team41/boromi/BoromiApp.java
  app/src/main/java/com/team41/boromi/book/SettingsFragment.java
  app/src/main/java/com/team41/boromi/controllers/AuthenticationController.java
  app/src/main/java/com/team41/boromi/dagger/AuthenticationComponent.java
Labels: Length: Less than 5 Hours

#82 Andrew/more integration
  app/src/main/java/com/team41/boromi/BookActivity.java
  app/src/main/java/com/team41/boromi/adapters/GenericListAdapter.java
  app/src/main/java/com/team41/boromi/adapters/PagerAdapter.java
  app/src/main/java/com/team41/boromi/adapters/SubListAdapter.java
  app/src/main/java/com/team41/boromi/auth/LoginFragment.java
  app/src/main/java/com/team41/boromi/auth/RecoverPasswordFragment.java
  app/src/main/java/com/team41/boromi/auth/SignupFragment.java
  app/src/main/java/com/team41/boromi/auth/WelcomeFragment.java
  app/src/main/java/com/team41/boromi/book/AddBookFragment.java
  app/src/main/java/com/team41/boromi/book/BorrowedFragment.java
  app/src/main/java/com/team41/boromi/book/EditBookFragment.java
  app/src/main/java/com/team41/boromi/book/EditUserFragment.java
  app/src/main/java/com/team41/boromi/book/GenericListFragment.java
  app/src/main/java/com/team41/boromi/book/OwnedFragment.java
  app/src/main/java/com/team41/boromi/book/SearchFragment.java
  app/src/main/java/com/team41/boromi/book/SettingsFragment.java
  app/src/main/java/com/team41/boromi/callbacks/AuthNoResultCallback.java
  app/src/main/java/com/team41/boromi/controllers/AuthenticationController.java
  app/src/main/java/com/team41/boromi/controllers/BookController.java
  app/src/main/java/com/team41/boromi/controllers/BookRequestController.java
  app/src/main/java/com/team41/boromi/dagger/AuthenticationComponent.java
  app/src/main/java/com/team41/boromi/dbs/BookDB.java
  app/src/main/java/com/team41/boromi/dbs/UserDB.java
  app/src/main/java/com/team41/boromi/utility/CustomClickListener.java
  app/src/main/res/layout/reqbm.xml
  app/src/test/java/com/team41/boromi/controllers/BookRequestControllerTest.java
Labels: Priority: Critical

#90 documentation
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/team41/boromi/BookActivity.java
  app/src/main/java/com/team41/boromi/FragmentFactory.java
  app/src/main/java/com/team41/boromi/MainActivity.java
  app/src/main/java/com/team41/boromi/TestActivity.java
  app/src/main/java/com/team41/boromi/TestRequestBookActivity.java
  app/src/main/java/com/team41/boromi/adapters/GenericListAdapter.java
  app/src/main/java/com/team41/boromi/adapters/PagerAdapter.java
  app/src/main/java/com/team41/boromi/adapters/SubListAdapter.java
  app/src/main/java/com/team41/boromi/auth/LoginFragment.java
  app/src/main/java/com/team41/boromi/auth/RecoverPasswordFragment.java
  app/src/main/java/com/team41/boromi/auth/SignupFragment.java
  app/src/main/java/com/team41/boromi/auth/WelcomeFragment.java
  app/src/main/java/com/team41/boromi/book/AddBookFragment.java
  app/src/main/java/com/team41/boromi/book/BorrowedFragment.java
  app/src/main/java/com/team41/boromi/book/EditBookFragment.java
  app/src/main/java/com/team41/boromi/book/EditUserFragment.java
  app/src/main/java/com/team41/boromi/book/GenericListFragment.java
  app/src/main/java/com/team41/boromi/book/MapFragment.java
  app/src/main/java/com/team41/boromi/book/OwnedFragment.java
  app/src/main/java/com/team41/boromi/book/SearchFragment.java
  app/src/main/java/com/team41/boromi/book/SettingsFragment.java
  app/src/main/java/com/team41/boromi/callbacks/AuthNoResultCallback.java
  app/src/main/java/com/team41/boromi/callbacks/BookRequestCallback.java
  app/src/main/java/com/team41/boromi/callbacks/ReturnCallback.java
  app/src/main/java/com/team41/boromi/constants/CommonConstants.java
  app/src/main/java/com/team41/boromi/controllers/AuthenticationController.java
  app/src/main/java/com/team41/boromi/controllers/BookController.java
  app/src/main/java/com/team41/boromi/controllers/BookRequestController.java
  app/src/main/java/com/team41/boromi/controllers/BookReturnController.java
  app/src/main/java/com/team41/boromi/dagger/AppComponent.java
  app/src/main/java/com/team41/boromi/dagger/AuthenticationComponent.java
  app/src/main/java/com/team41/boromi/dbs/BookDB.java
  app/src/main/java/com/team41/boromi/dbs/BookRequestDB.java
  app/src/main/java/com/team41/boromi/dbs/BookReturnDB.java
  app/src/main/java/com/team41/boromi/dbs/UserDB.java
  app/src/main/java/com/team41/boromi/models/BorrowerInterface.java
  app/src/main/java/com/team41/boromi/models/OwnerInterface.java
  app/src/main/java/com/team41/boromi/models/User.java
  app/src/main/java/com/team41/boromi/utility/CustomClickListener.java
  app/src/main/java/com/team41/boromi/utility/Utility.java
  app/src/main/res/layout/activity_test.xml
  app/src/main/res/layout/activity_test_request_book.xml
Labels: Type: Documentation

#113 User can set location on map and view location on map
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/team41/boromi/BookActivity.java
  app/src/main/java/com/team41/boromi/BookViewModel.java
  app/src/main/java/com/team41/boromi/FragmentFactory.java
  app/src/main/java/com/team41/boromi/MainActivity.java
  app/src/main/java/com/team41/boromi/ViewModelFactory.java
  app/src/main/java/com/team41/boromi/adapters/GenericListAdapter.java
  app/src/main/java/com/team41/boromi/adapters/PagerAdapter.java
  app/src/main/java/com/team41/boromi/adapters/SubListAdapter.java
  app/src/main/java/com/team41/boromi/auth/LoginFragment.java
  app/src/main/java/com/team41/boromi/auth/RecoverPasswordFragment.java
  app/src/main/java/com/team41/boromi/auth/SignupFragment.java
  app/src/main/java/com/team41/boromi/auth/WelcomeFragment.java
  app/src/main/java/com/team41/boromi/book/AddBookFragment.java
  app/src/main/java/com/team41/boromi/book/BorrowedFragment.java
  app/src/main/java/com/team41/boromi/book/EditBookFragment.java
  app/src/main/java/com/team41/boromi/book/EditUserFragment.java
  app/src/main/java/com/team41/boromi/book/GenericListFragment.java
  app/src/main/java/com/team41/boromi/book/MapFragment.java
  app/src/main/java/com/team41/boromi/book/OwnedFragment.java
  app/src/main/java/com/team41/boromi/book/SearchFragment.java
  app/src/main/java/com/team41/boromi/book/SettingsFragment.java
  app/src/main/java/com/team41/boromi/controllers/AuthenticationController.java
  app/src/main/java/com/team41/boromi/controllers/BookController.java
  app/src/main/java/com/team41/boromi/controllers/BookRequestController.java
  app/src/main/java/com/team41/boromi/controllers/BookReturnController.java
  app/src/main/java/com/team41/boromi/dbs/BookDB.java
  app/src/main/java/com/team41/boromi/dbs/BookRequestDB.java
  app/src/main/java/com/team41/boromi/dbs/UserDB.java
  app/src/main/java/com/team41/boromi/models/Book.java
  app/src/main/java/com/team41/boromi/models/BookRequest.java
  app/src/main/java/com/team41/boromi/models/BookReturn.java
  app/src/main/java/com/team41/boromi/utility/CustomClickListener.java
  app/src/main/res/layout/fragment_map.xml
  secure.properties
Labels: Length: 10-20 Hours, Priority: Critical, Type: Core

#115 Implemented a cloud function to send notifications on accepted request
  functions/src/index.ts
Labels: Length: Less than 5 Hours

#114 added barcode for exchanging
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/team41/boromi/MainActivity.java
  app/src/main/java/com/team41/boromi/book/AddBookFragment.java
  app/src/main/java/com/team41/boromi/book/GenericListFragment.java
  app/src/main/java/com/team41/boromi/utility/CustomClickListener.java
  app/src/main/res/layout/add_book_fragment.xml
Labels: Length: 5-10 Hours

#125 Fixed Scaling of Book Images
  app/src/main/java/com/team41/boromi/adapters/GenericListAdapter.java
Labels: Length: Less than 5 Hours, Priority: Low, Status: Available
