Repository CMPUT301F20T41/boromi, pull requests merged in 2020-10, with the labels that each got.

#5 Create License.md
  License.md
Labels: Priority: Medium

#6 Added basic build CI and Initiated project on API Level 26 / Oreo 8.0
  .github/workflows/ci-build-check.yaml
  .gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/team41/boromi/ExampleInstrumentedTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/team41/boromi/MainActivity.java
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/com/team41/boromi/ExampleUnitTest.java
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: Priority: Low, Type: Maintenance

#13 Closes #9, Added the initial classes
  app/src/main/java/com/team41/boromi/constants/CommonConstants.java
  app/src/main/java/com/team41/boromi/models/Book.java
  app/src/main/java/com/team41/boromi/models/BookRequest.java
  app/src/main/java/com/team41/boromi/models/BookReturn.java
  app/src/main/java/com/team41/boromi/models/BorrowerInterface.java
  app/src/main/java/com/team41/boromi/models/OwnerInterface.java
  app/src/main/java/com/team41/boromi/models/User.java
Labels: Type: Core

#24 Added all image assets currently required by the project
  app/src/main/res/drawable/add_icon.xml
  app/src/main/res/drawable/add_photo_icon.xml
  app/src/main/res/drawable/arrow_back_icon.xml
  app/src/main/res/drawable/barcode_scan_icon.xml
  app/src/main/res/drawable/book_icon.xml
  app/src/main/res/drawable/cancel_icon.xml
  app/src/main/res/drawable/check_icon.xml
  app/src/main/res/drawable/delete_icon.xml
  app/src/main/res/drawable/edit_icon.xml
  app/src/main/res/drawable/location_icon.xml
  app/src/main/res/drawable/more_horizontal_icon.xml
  app/src/main/res/drawable/outgoing_icon.xml
  app/src/main/res/drawable/return_icon.xml
  app/src/main/res/drawable/search_icon.xml
  app/src/main/res/drawable/settings_icon.xml
  app/src/main/res/drawable/undraw_book_reader.xml
  app/src/main/res/drawable/undraw_book_reader_2.xml
  app/src/main/res/drawable/undraw_forgot_password.xml
Labels: Length: Less than 5 Hours, Priority: Medium

#21 Ming/user signup login #16
  app/build.gradle
  app/google-services.json
  app/src/androidTest/java/com/team41/boromi/ExampleInstrumentedTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/team41/boromi/BookActivity.java
  app/src/main/java/com/team41/boromi/BoromiApp.java
  app/src/main/java/com/team41/boromi/TestActivity.java
  app/src/main/java/com/team41/boromi/callbacks/AuthCallback.java
  app/src/main/java/com/team41/boromi/constants/CommonConstants.java
  app/src/main/java/com/team41/boromi/controllers/AuthenticationController.java
  app/src/main/java/com/team41/boromi/dagger/ActivityScope.java
  app/src/main/java/com/team41/boromi/dagger/AppComponent.java
  app/src/main/java/com/team41/boromi/dagger/AuthenticationComponent.java
  app/src/main/java/com/team41/boromi/dagger/BoromiModule.java
  app/src/main/java/com/team41/boromi/dagger/FirestoreModule.java
  app/src/main/java/com/team41/boromi/dbs/UserDB.java
  app/src/main/java/com/team41/boromi/models/Book.java
  app/src/main/java/com/team41/boromi/models/BookRequest.java
  app/src/main/java/com/team41/boromi/models/BookReturn.java
  app/src/main/java/com/team41/boromi/models/BorrowerInterface.java
  app/src/main/java/com/team41/boromi/models/OwnerInterface.java
  app/src/main/java/com/team41/boromi/models/User.java
  app/src/main/res/layout/activity_test.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/team41/boromi/ExampleUnitTest.java
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: Length: 10-20 Hours, Priority: Critical, Type: Core

#36 Added fields necessary to match the db schema and to be used in requesting
  .github/workflows/ci-build-check.yaml
  app/src/androidTest/java/com/team41/boromi/BookDBTest.java
  app/src/main/java/com/team41/boromi/models/Book.java
Labels: Length: Less than 5 Hours, Priority: Critical

#43 Added the boromi logo
  app/src/main/res/drawable/logo_boromi_text.xml
Labels: Length: Less than 5 Hours
